/**
 * Banque de questions du quiz. SERVEUR SEULEMENT : seul le moteur (src/lib/multiplayer-
 * engines.ts) l'importe. Elle porte les bonnes réponses : importée par un composant, elle
 * finirait dans le JavaScript envoyé au navigateur et n'importe quel joueur les y lirait.
 *
 * CONVENTION : la bonne réponse est TOUJOURS le premier choix. L'ordre est mélangé à
 * chaque question posée (voir `quizQuestion`), sa position ne se devine donc pas en jeu —
 * et l'écrire toujours en tête évite de se tromper d'indice en ajoutant une question.
 *
 * Pour ajouter une question : une ligne dans le bon thème, bonne réponse d'abord, trois
 * leurres plausibles ensuite. Au moins 20 questions par thème.
 */

export type QuizBankEntry = {
  category: string;
  text: string;
  /** Quatre choix, la bonne réponse en premier. */
  choices: [string, string, string, string];
};

type Question = [text: string, choices: [string, string, string, string]];

function theme(category: string, questions: Question[]): QuizBankEntry[] {
  return questions.map(([text, choices]) => ({ category, text, choices }));
}

export const QUIZ_BANK: QuizBankEntry[] = [
  ...theme("Géographie", [
    ["Quelle est la capitale de l'Australie ?", ["Canberra", "Sydney", "Melbourne", "Perth"]],
    ["Quel est le plus long fleuve de France ?", ["La Loire", "La Seine", "Le Rhône", "La Garonne"]],
    ["Combien de pays partagent une frontière terrestre avec la France métropolitaine ?", ["8", "6", "7", "9"]],
    ["Quel est le plus haut sommet d'Afrique ?", ["Le Kilimandjaro", "Le mont Kenya", "Le mont Stanley", "Le Ras Dashen"]],
    ["Dans quel pays se trouve la ville de Marrakech ?", ["Le Maroc", "L'Algérie", "La Tunisie", "L'Égypte"]],
    ["Quel océan borde la côte ouest des États-Unis ?", ["Le Pacifique", "L'Atlantique", "L'océan Indien", "L'Arctique"]],
    ["Quelle est la capitale du Canada ?", ["Ottawa", "Toronto", "Montréal", "Vancouver"]],
    ["Quel est le plus grand désert chaud du monde ?", ["Le Sahara", "Le Kalahari", "Le Gobi", "L'Atacama"]],
    ["Combien de régions compte la France métropolitaine depuis 2016 ?", ["13", "12", "18", "22"]],
    ["Quelle mer sépare l'Europe de l'Afrique ?", ["La Méditerranée", "La mer Noire", "La mer Rouge", "La mer Caspienne"]],
    ["Quelle est la capitale du Japon ?", ["Tokyo", "Kyoto", "Osaka", "Hiroshima"]],
    ["Quel est le plus grand pays du monde par sa superficie ?", ["La Russie", "Le Canada", "La Chine", "Les États-Unis"]],
    ["Le sommet du mont Blanc se trouve à la frontière entre la France et…", ["L'Italie", "La Suisse", "L'Autriche", "L'Allemagne"]],
    ["Quel est le plus long fleuve d'Amérique du Sud ?", ["L'Amazone", "Le Paraná", "L'Orénoque", "Le Magdalena"]],
    ["Quelle est la capitale du Brésil ?", ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"]],
    ["Quel pays a la forme d'une botte ?", ["L'Italie", "La Grèce", "Le Portugal", "La Croatie"]],
    ["Dans quelle ville se trouve la Sagrada Família ?", ["Barcelone", "Madrid", "Séville", "Valence"]],
    ["Quelle est la capitale de la Norvège ?", ["Oslo", "Stockholm", "Copenhague", "Helsinki"]],
    ["Quel détroit sépare l'Espagne du Maroc ?", ["Le détroit de Gibraltar", "Le Bosphore", "Le détroit de Messine", "Le détroit d'Ormuz"]],
    ["Quelle est la plus grande île de la Méditerranée ?", ["La Sicile", "La Sardaigne", "Chypre", "La Corse"]],
  ]),

  ...theme("Histoire", [
    ["En quelle année a eu lieu la prise de la Bastille ?", ["1789", "1776", "1799", "1815"]],
    ["Qui a été le premier président de la Ve République ?", ["Charles de Gaulle", "Georges Pompidou", "René Coty", "Vincent Auriol"]],
    ["En quelle année le mur de Berlin est-il tombé ?", ["1989", "1987", "1991", "1993"]],
    ["Quel empereur a été sacré à Notre-Dame de Paris en 1804 ?", ["Napoléon Ier", "Charlemagne", "Louis XVIII", "Napoléon III"]],
    ["Quelle civilisation a construit le Machu Picchu ?", ["Les Incas", "Les Aztèques", "Les Mayas", "Les Olmèques"]],
    ["En quelle année les billets et pièces en euros sont-ils entrés en circulation ?", ["2002", "1999", "2000", "2004"]],
    ["Qui a écrit le « Manifeste du parti communiste » avec Karl Marx ?", ["Friedrich Engels", "Lénine", "Léon Trotski", "Pierre-Joseph Proudhon"]],
    ["Quel paquebot a coulé lors de son voyage inaugural en 1912 ?", ["Le Titanic", "Le Lusitania", "Le Britannic", "Le Normandie"]],
    ["Quelle reine de France était surnommée « l'Autrichienne » ?", ["Marie-Antoinette", "Catherine de Médicis", "Anne d'Autriche", "Marie de Médicis"]],
    ["En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", ["1969", "1965", "1967", "1972"]],
    ["En quelle année a commencé la Première Guerre mondiale ?", ["1914", "1912", "1916", "1918"]],
    ["Quel roi de France était surnommé le « Roi-Soleil » ?", ["Louis XIV", "Louis XIII", "Louis XV", "Louis XVI"]],
    ["En quelle année a eu lieu la bataille de Waterloo ?", ["1815", "1805", "1812", "1830"]],
    ["Quel navigateur a atteint l'Amérique en 1492 ?", ["Christophe Colomb", "Vasco de Gama", "Fernand de Magellan", "Amerigo Vespucci"]],
    ["Quelle héroïne a délivré Orléans en 1429 ?", ["Jeanne d'Arc", "Aliénor d'Aquitaine", "Catherine de Médicis", "Blanche de Castille"]],
    ["En quelle année les Françaises ont-elles voté pour la première fois ?", ["1945", "1919", "1936", "1958"]],
    ["Quel pharaon a un tombeau découvert presque intact par Howard Carter en 1922 ?", ["Toutânkhamon", "Ramsès II", "Khéops", "Akhenaton"]],
    ["Quelle ville romaine a été ensevelie par l'éruption du Vésuve en 79 ?", ["Pompéi", "Rome", "Naples", "Carthage"]],
    ["Qui a été le premier empereur romain ?", ["Auguste", "Jules César", "Néron", "Caligula"]],
    ["En quelle année la Seconde Guerre mondiale s'est-elle terminée en Europe ?", ["1945", "1943", "1944", "1946"]],
  ]),

  ...theme("Sciences", [
    ["Quel est le symbole chimique de l'or ?", ["Au", "Ag", "Or", "Go"]],
    ["Quelle planète est la plus proche du Soleil ?", ["Mercure", "Vénus", "Mars", "La Terre"]],
    ["Combien d'os compte le squelette d'un humain adulte ?", ["206", "186", "226", "256"]],
    ["Quel gaz les plantes absorbent-elles pour la photosynthèse ?", ["Le dioxyde de carbone", "L'oxygène", "L'azote", "L'hélium"]],
    ["À quelle température l'eau bout-elle au niveau de la mer ?", ["100 °C", "90 °C", "110 °C", "120 °C"]],
    ["Qui a formulé la théorie de la relativité ?", ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"]],
    ["Quelle est la plus grosse planète du système solaire ?", ["Jupiter", "Saturne", "Neptune", "Uranus"]],
    ["Quel organe produit l'insuline ?", ["Le pancréas", "Le foie", "Les reins", "La rate"]],
    ["Quelle est la vitesse approximative de la lumière dans le vide ?", ["300 000 km/s", "150 000 km/s", "30 000 km/s", "1 000 000 km/s"]],
    ["Combien de chromosomes possède une cellule humaine ordinaire ?", ["46", "23", "44", "48"]],
    ["Quelle est la formule chimique de l'eau ?", ["H₂O", "CO₂", "O₂", "H₂O₂"]],
    ["Quelle planète est surnommée la « planète rouge » ?", ["Mars", "Vénus", "Jupiter", "Mercure"]],
    ["Quel est le gaz le plus abondant dans l'air que nous respirons ?", ["L'azote", "L'oxygène", "Le dioxyde de carbone", "L'argon"]],
    ["Qui a découvert la pénicilline ?", ["Alexander Fleming", "Louis Pasteur", "Marie Curie", "Robert Koch"]],
    ["Combien de cavités compte le cœur humain ?", ["4", "2", "3", "6"]],
    ["Quel est le plus grand organe du corps humain ?", ["La peau", "Le foie", "Les poumons", "L'intestin"]],
    ["Quelle scientifique a reçu un prix Nobel en physique ET en chimie ?", ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Lise Meitner"]],
    ["Combien de planètes compte le système solaire ?", ["8", "7", "9", "10"]],
    ["Quel est le symbole chimique du fer ?", ["Fe", "Fr", "F", "Ir"]],
    ["En quelle unité mesure-t-on la résistance électrique ?", ["L'ohm", "Le volt", "L'ampère", "Le watt"]],
  ]),

  ...theme("Arts & lettres", [
    ["Qui a peint « La Joconde » ?", ["Léonard de Vinci", "Michel-Ange", "Raphaël", "Botticelli"]],
    ["Qui a écrit « Les Misérables » ?", ["Victor Hugo", "Émile Zola", "Gustave Flaubert", "Honoré de Balzac"]],
    ["Dans quel musée est exposée la Vénus de Milo ?", ["Le Louvre", "Le musée d'Orsay", "Le British Museum", "Le musée du Prado"]],
    ["Qui est l'auteur du « Petit Prince » ?", ["Antoine de Saint-Exupéry", "Jules Verne", "Albert Camus", "Marcel Pagnol"]],
    ["Quel peintre s'est tranché une partie de l'oreille ?", ["Vincent van Gogh", "Paul Gauguin", "Claude Monet", "Paul Cézanne"]],
    ["Qui a écrit « Roméo et Juliette » ?", ["William Shakespeare", "Molière", "Jean Racine", "Goethe"]],
    ["Quel mouvement le tableau « Impression, soleil levant » de Monet a-t-il nommé ?", ["L'impressionnisme", "Le cubisme", "Le surréalisme", "Le fauvisme"]],
    ["Qui a écrit « Les Fleurs du mal » ?", ["Charles Baudelaire", "Arthur Rimbaud", "Paul Verlaine", "Victor Hugo"]],
    ["Qui a peint « Guernica » ?", ["Pablo Picasso", "Salvador Dalí", "Joan Miró", "Francisco de Goya"]],
    ["Qui est l'auteur de « Madame Bovary » ?", ["Gustave Flaubert", "Honoré de Balzac", "Émile Zola", "Stendhal"]],
    ["Qui a sculpté « Le Penseur » ?", ["Auguste Rodin", "Camille Claudel", "Michel-Ange", "Aristide Maillol"]],
    ["Qui a écrit « L'Étranger » ?", ["Albert Camus", "Jean-Paul Sartre", "André Gide", "André Malraux"]],
    ["Quel dramaturge a écrit « Le Malade imaginaire » ?", ["Molière", "Jean Racine", "Pierre Corneille", "Marivaux"]],
    ["Qui a peint « La Persistance de la mémoire », aux montres molles ?", ["Salvador Dalí", "René Magritte", "Max Ernst", "Marc Chagall"]],
    ["Qui a écrit « Vingt mille lieues sous les mers » ?", ["Jules Verne", "Alexandre Dumas", "Victor Hugo", "Guy de Maupassant"]],
    ["Qui a écrit « Les Trois Mousquetaires » ?", ["Alexandre Dumas", "Victor Hugo", "Jules Verne", "Honoré de Balzac"]],
    ["Quel peintre néerlandais a peint « La Jeune Fille à la perle » ?", ["Johannes Vermeer", "Rembrandt", "Vincent van Gogh", "Pieter Bruegel"]],
    ["Qui est l'auteur du « Seigneur des anneaux » ?", ["J. R. R. Tolkien", "C. S. Lewis", "George R. R. Martin", "J. K. Rowling"]],
    ["Qui a écrit « 1984 » ?", ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H. G. Wells"]],
    ["Quel sculpteur français a conçu la statue de la Liberté ?", ["Frédéric Auguste Bartholdi", "Auguste Rodin", "Gustave Eiffel", "Aristide Maillol"]],
  ]),

  ...theme("Sport", [
    ["Combien de joueurs compte une équipe de football sur le terrain ?", ["11", "9", "10", "12"]],
    ["Dans quelle ville se sont tenus les Jeux olympiques d'été de 2024 ?", ["Paris", "Tokyo", "Los Angeles", "Londres"]],
    ["Combien de sets faut-il gagner pour remporter un match masculin en Grand Chelem ?", ["3", "2", "4", "5"]],
    ["Quelle est la distance officielle d'un marathon ?", ["42,195 km", "40 km", "45 km", "50 km"]],
    ["Quel pays a remporté la Coupe du monde de football 2018 ?", ["La France", "La Croatie", "L'Allemagne", "Le Brésil"]],
    ["Dans quel sport utilise-t-on un volant ?", ["Le badminton", "Le squash", "Le tennis de table", "Le padel"]],
    ["Combien de points vaut un essai au rugby à XV ?", ["5", "3", "4", "7"]],
    ["Combien de joueurs une équipe de basket a-t-elle sur le terrain ?", ["5", "4", "6", "7"]],
    ["Quel tournoi du Grand Chelem se joue sur terre battue ?", ["Roland-Garros", "Wimbledon", "L'US Open", "L'Open d'Australie"]],
    ["Combien de fois l'équipe de France masculine a-t-elle gagné la Coupe du monde de football ?", ["2", "1", "3", "4"]],
    ["Dans quel sport Teddy Riner s'est-il illustré ?", ["Le judo", "La lutte", "La boxe", "Le rugby"]],
    ["De quelle couleur est le maillot du leader du classement général du Tour de France ?", ["Jaune", "Vert", "Blanc", "À pois rouges"]],
    ["Combien de trous compte un parcours de golf standard ?", ["18", "9", "12", "24"]],
    ["Tous les combien d'années ont lieu les Jeux olympiques d'été ?", ["4 ans", "2 ans", "3 ans", "5 ans"]],
    ["Dans quel pays le judo est-il né ?", ["Le Japon", "La Chine", "La Corée", "La Thaïlande"]],
    ["Quel nageur détient le record de médailles d'or olympiques ?", ["Michael Phelps", "Mark Spitz", "Ian Thorpe", "Léon Marchand"]],
    ["Combien de joueurs une équipe de volley-ball a-t-elle sur le terrain ?", ["6", "5", "7", "8"]],
    ["Quel sport se joue sur la glace avec une crosse et un palet ?", ["Le hockey sur glace", "Le curling", "Le bandy", "La crosse"]],
    ["Quel est le surnom de l'équipe de France de football ?", ["Les Bleus", "Les Rouges", "Les Diables", "Les Lions"]],
    ["Dans quelle ville se court la plus célèbre course automobile d'endurance de 24 heures ?", ["Le Mans", "Spa", "Monaco", "Magny-Cours"]],
  ]),

  ...theme("Musique", [
    ["Quel groupe a chanté « Bohemian Rhapsody » ?", ["Queen", "The Beatles", "Led Zeppelin", "Pink Floyd"]],
    ["Quelle chanteuse était surnommée « la Môme » ?", ["Édith Piaf", "Dalida", "Barbara", "Juliette Gréco"]],
    ["Combien de cordes possède une guitare classique ?", ["6", "4", "5", "7"]],
    ["Quel compositeur est devenu sourd au cours de sa vie ?", ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Jean-Sébastien Bach", "Frédéric Chopin"]],
    ["Qui chante « Thriller » ?", ["Michael Jackson", "Prince", "Stevie Wonder", "Lionel Richie"]],
    ["Combien de touches compte un piano standard ?", ["88", "76", "92", "100"]],
    ["Quel groupe réunissait John, Paul, George et Ringo ?", ["The Beatles", "The Rolling Stones", "The Who", "The Kinks"]],
    ["Qui a composé « Les Quatre Saisons » ?", ["Antonio Vivaldi", "Jean-Sébastien Bach", "Wolfgang Amadeus Mozart", "Joseph Haydn"]],
    ["Quel rappeur français a sorti l'album « Civilisation » en 2021 ?", ["Orelsan", "Nekfeu", "Booba", "Damso"]],
    ["Quel duo français a sorti le tube « Get Lucky » ?", ["Daft Punk", "Justice", "Air", "Cassius"]],
    ["Combien de notes compte la gamme do, ré, mi, fa, sol, la, si ?", ["7", "5", "8", "12"]],
    ["Quel est l'hymne national français ?", ["La Marseillaise", "Le Chant du départ", "L'Internationale", "La Carmagnole"]],
    ["Qui a composé l'opéra « La Flûte enchantée » ?", ["Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Giuseppe Verdi", "Richard Wagner"]],
    ["De quel pays vient le groupe ABBA ?", ["La Suède", "La Norvège", "Le Danemark", "La Finlande"]],
    ["Quelle chanteuse a interprété « Rolling in the Deep » ?", ["Adele", "Amy Winehouse", "Duffy", "Rihanna"]],
    ["De quelle nationalité est le chanteur Stromae ?", ["Belge", "Française", "Suisse", "Canadienne"]],
    ["Lequel de ces instruments se joue avec un archet ?", ["Le violon", "La guitare", "Le piano", "La trompette"]],
    ["Quel chanteur était surnommé « l'idole des jeunes » ?", ["Johnny Hallyday", "Eddy Mitchell", "Claude François", "Michel Sardou"]],
    ["Quel chanteur était surnommé « le King » ?", ["Elvis Presley", "Michael Jackson", "Frank Sinatra", "Chuck Berry"]],
    ["Combien de musiciens compte un quatuor ?", ["4", "3", "5", "6"]],
  ]),

  ...theme("Films & séries", [
    ["Qui a réalisé « Le Fabuleux Destin d'Amélie Poulain » ?", ["Jean-Pierre Jeunet", "Luc Besson", "Jacques Audiard", "Michel Gondry"]],
    ["Quel film a remporté le premier Oscar du meilleur film d'animation ?", ["Shrek", "Toy Story", "Le Roi lion", "Monstres et Cie"]],
    ["Dans quelle ville se déroule le plus célèbre festival de cinéma de France ?", ["Cannes", "Deauville", "Annecy", "Nice"]],
    ["Qui a réalisé « Titanic » (1997) ?", ["James Cameron", "Steven Spielberg", "Ridley Scott", "Francis Ford Coppola"]],
    ["Dans « Star Wars », qui est le père de Luke Skywalker ?", ["Dark Vador", "Obi-Wan Kenobi", "Yoda", "L'empereur Palpatine"]],
    ["Dans « Breaking Bad », quel est le métier de Walter White au début de la série ?", ["Professeur de chimie", "Médecin", "Avocat", "Policier"]],
    ["Dans quelle série trouve-t-on les familles Stark et Lannister ?", ["Game of Thrones", "The Witcher", "Vikings", "Les Anneaux de pouvoir"]],
    ["Quel film français de 2011 réunit Omar Sy et François Cluzet ?", ["Intouchables", "Bienvenue chez les Ch'tis", "Le Dîner de cons", "Les Visiteurs"]],
    ["Comment s'appelle le jeune sorcier à la cicatrice en forme d'éclair ?", ["Harry Potter", "Merlin", "Gandalf", "Albus Dumbledore"]],
    ["Dans « Le Roi lion », comment s'appelle le père de Simba ?", ["Mufasa", "Scar", "Rafiki", "Zazu"]],
    ["Quelle série se déroule à Hawkins, avec le « Monde à l'envers » ?", ["Stranger Things", "Dark", "The OA", "Riverdale"]],
    ["Quel acteur incarne le capitaine Jack Sparrow ?", ["Johnny Depp", "Orlando Bloom", "Brad Pitt", "Leonardo DiCaprio"]],
    ["Dans « Friends », quel est le métier de Ross ?", ["Paléontologue", "Cuisinier", "Acteur", "Comptable"]],
    ["Quelle série espagnole met en scène « le Professeur » et une bande de braqueurs ?", ["La casa de papel", "Élite", "Narcos", "Vis a vis"]],
    ["Qui a réalisé « Pulp Fiction » ?", ["Quentin Tarantino", "Martin Scorsese", "Joel Coen", "Guy Ritchie"]],
    ["Dans quel film de la saga « Star Wars » Dark Vador révèle-t-il être le père de Luke ?", ["L'Empire contre-attaque", "Un nouvel espoir", "Le Retour du Jedi", "La Menace fantôme"]],
    ["Quel super-héros se cache derrière Tony Stark ?", ["Iron Man", "Captain America", "Thor", "Hulk"]],
    ["Quelle série retrace le règne de la reine Élisabeth II ?", ["The Crown", "Downton Abbey", "Victoria", "Peaky Blinders"]],
    ["Dans « Toy Story », comment s'appelle le cow-boy ?", ["Woody", "Buzz", "Rex", "Zig-Zag"]],
    ["Qui a réalisé « Jurassic Park » (1993) ?", ["Steven Spielberg", "George Lucas", "James Cameron", "Robert Zemeckis"]],
    ["Quel acteur incarne Assane Diop dans la série « Lupin » ?", ["Omar Sy", "Jamel Debbouze", "Vincent Cassel", "Jean Dujardin"]],
  ]),

  ...theme("Animé & manga", [
    ["Dans « One Piece », quel est le rêve de Luffy ?", ["Devenir le roi des pirates", "Devenir Hokage", "Devenir maître Pokémon", "Réunir les Dragon Balls"]],
    ["Dans « Naruto », comment s'appelle le renard à neuf queues ?", ["Kurama", "Shukaku", "Gyûki", "Matatabi"]],
    ["Qui est l'auteur de « Dragon Ball » ?", ["Akira Toriyama", "Eiichirō Oda", "Masashi Kishimoto", "Tite Kubo"]],
    ["Comment s'appelle le personnage principal de « L'Attaque des Titans » ?", ["Eren Jäger", "Levi Ackerman", "Armin Arlelt", "Erwin Smith"]],
    ["Quel studio a produit « Le Voyage de Chihiro » ?", ["Le studio Ghibli", "Toei Animation", "Madhouse", "Studio Pierrot"]],
    ["Qui a réalisé « Mon voisin Totoro » ?", ["Hayao Miyazaki", "Isao Takahata", "Makoto Shinkai", "Mamoru Hosoda"]],
    ["Dans « Death Note », quel dieu de la mort accompagne Light ?", ["Ryûk", "Rem", "L", "Misa"]],
    ["Quel Pokémon accompagne Sacha dans l'anime ?", ["Pikachu", "Évoli", "Salamèche", "Rondoudou"]],
    ["Dans « Dragon Ball », quel est le nom saiyan de Son Goku ?", ["Kakarot", "Vegeta", "Raditz", "Bardock"]],
    ["Dans « Naruto », quel est le village natal du héros ?", ["Konoha", "Suna", "Kiri", "Kumo"]],
    ["Dans « Jujutsu Kaisen », quel professeur porte un bandeau sur les yeux ?", ["Satoru Gojo", "Ryômen Sukuna", "Megumi Fushiguro", "Kento Nanami"]],
    ["Dans « Demon Slayer », quel héros veut rendre sa sœur Nezuko humaine ?", ["Tanjirō Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Giyū Tomioka"]],
    ["Quel fruit du démon Luffy a-t-il mangé ?", ["Le fruit du Gum-Gum", "Le fruit du Pyro-Pyro", "Le fruit du Givre-Givre", "Le fruit du Bara-Bara"]],
    ["Dans quel manga trouve-t-on les Chevaliers du Zodiaque ?", ["Saint Seiya", "Bleach", "Fairy Tail", "Hunter × Hunter"]],
    ["Dans « Fullmetal Alchemist », quel frère vit dans une armure ?", ["Alphonse Elric", "Edward Elric", "Roy Mustang", "Van Hohenheim"]],
    ["Dans quel sens se lit un manga japonais traditionnel ?", ["De droite à gauche", "De gauche à droite", "De haut en bas", "De bas en haut"]],
    ["Comment appelle-t-on un manga destiné en priorité aux jeunes garçons ?", ["Un shōnen", "Un shōjo", "Un seinen", "Un josei"]],
    ["Dans « My Hero Academia », quel héros naît sans pouvoir ?", ["Izuku Midoriya", "Katsuki Bakugō", "Shōto Todoroki", "All Might"]],
    ["Dans « Hunter × Hunter », quel jeune héros part à la recherche de son père ?", ["Gon Freecss", "Killua Zoldyck", "Kurapika", "Leorio"]],
    ["Dans quel magazine japonais paraît « One Piece » ?", ["Weekly Shōnen Jump", "Weekly Shōnen Magazine", "Weekly Shōnen Sunday", "Ribon"]],
  ]),

  ...theme("Jeux vidéo", [
    ["Comment s'appelle le célèbre plombier moustachu de Nintendo ?", ["Mario", "Luigi", "Wario", "Toad"]],
    ["Dans « The Legend of Zelda », comment s'appelle le héros ?", ["Link", "Zelda", "Ganon", "Epona"]],
    ["Quelle entreprise a créé la PlayStation ?", ["Sony", "Nintendo", "Microsoft", "Sega"]],
    ["Quel est le jeu vidéo le plus vendu de tous les temps ?", ["Minecraft", "GTA V", "Tetris", "Wii Sports"]],
    ["Quel hérisson bleu est la mascotte de Sega ?", ["Sonic", "Crash", "Spyro", "Knuckles"]],
    ["Dans quel jeu affronte-t-on des Creepers dans un monde de blocs ?", ["Minecraft", "Roblox", "Terraria", "Fortnite"]],
    ["Quel studio français a créé la saga « Assassin's Creed » ?", ["Ubisoft", "Quantic Dream", "Dontnod", "Arkane"]],
    ["Quelle console de Nintendo est sortie en 2017 ?", ["La Nintendo Switch", "La Wii U", "La Wii", "La GameCube"]],
    ["Dans « Street Fighter », quel personnage est connu pour son « Hadoken » ?", ["Ryu", "Chun-Li", "Guile", "Blanka"]],
    ["Quel jeu de Riot Games oppose deux équipes de cinq champions ?", ["League of Legends", "Dota 2", "Valorant", "Overwatch"]],
    ["De quelle saga Kratos est-il le héros ?", ["God of War", "Devil May Cry", "Bayonetta", "Dark Souls"]],
    ["Dans « Pokémon Rouge et Bleu », quel est le Pokémon de départ de type Plante ?", ["Bulbizarre", "Germignon", "Arcko", "Tortipouss"]],
    ["Quel studio a développé « The Witcher 3 » ?", ["CD Projekt Red", "Bethesda", "BioWare", "Ubisoft"]],
    ["Quel jeu de 1984 consiste à empiler des pièces qui tombent ?", ["Tetris", "Pong", "Snake", "Space Invaders"]],
    ["Dans « Super Mario », comment s'appelle la princesse du royaume Champignon ?", ["Peach", "Daisy", "Zelda", "Harmonie"]],
    ["Quelle saga se déroule notamment dans la ville fictive de Los Santos ?", ["Grand Theft Auto", "Watch Dogs", "Saints Row", "Mafia"]],
    ["Qui a créé Mario et « The Legend of Zelda » ?", ["Shigeru Miyamoto", "Hideo Kojima", "Satoru Iwata", "Yuji Naka"]],
    ["Dans « Among Us », comment appelle-t-on le traître ?", ["L'imposteur", "Le saboteur", "Le loup", "L'espion"]],
    ["Quelle console Microsoft a-t-il lancée en 2001 ?", ["La Xbox", "La Dreamcast", "La GameCube", "La PlayStation 2"]],
    ["Que mange Pac-Man dans le labyrinthe ?", ["Des pac-gommes", "Des pièces d'or", "Des champignons", "Des étoiles"]],
  ]),

  ...theme("Vie de bureau", [
    ["Que signifie « CRA » dans le conseil en informatique ?", ["Compte rendu d'activité", "Contrat de recrutement annuel", "Calendrier des ressources affectées", "Charte de responsabilité"]],
    ["Combien de jours ouvrés de congés payés un salarié à temps plein acquiert-il par an en France ?", ["25", "20", "30", "35"]],
    ["Que signifie « ESN » ?", ["Entreprise de services du numérique", "École supérieure du numérique", "Ensemble de solutions numériques", "Entreprise de support réseau"]],
    ["Quel raccourci clavier annule la dernière action dans la plupart des logiciels ?", ["Ctrl + Z", "Ctrl + Y", "Ctrl + X", "Ctrl + U"]],
    ["Que désigne « RTT » ?", ["Réduction du temps de travail", "Repos temporaire total", "Rémunération du travail tardif", "Règlement du télétravail"]],
    ["Que signifie « CDI » ?", ["Contrat à durée indéterminée", "Contrat de développement individuel", "Convention de durée indicative", "Contrat d'insertion"]],
    ["Que signifie « CDD » ?", ["Contrat à durée déterminée", "Contrat de droit dérogatoire", "Convention de détachement", "Contrat de dernière durée"]],
    ["Quelle est la durée légale hebdomadaire du travail en France ?", ["35 heures", "32 heures", "39 heures", "40 heures"]],
    ["Que signifie « DRH » ?", ["Directeur des ressources humaines", "Délégué au recrutement et à l'habilitation", "Direction des relations hiérarchiques", "Département de la rémunération horaire"]],
    ["Que signifie « TJM » dans le conseil ?", ["Taux journalier moyen", "Temps de journée minimal", "Total des jours mensuels", "Tarif de jour majoré"]],
    ["Quel raccourci clavier copie la sélection ?", ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + P"]],
    ["Quelle est la durée maximale de la période d'essai initiale d'un cadre en CDI ?", ["4 mois", "2 mois", "3 mois", "6 mois"]],
    ["Que signifie « SMIC » ?", ["Salaire minimum interprofessionnel de croissance", "Salaire moyen indexé sur la croissance", "Seuil minimal d'indemnité conventionnelle", "Salaire mensuel interprofessionnel commun"]],
    ["Quel outil de Microsoft sert aux visioconférences et au chat d'équipe ?", ["Teams", "Outlook", "OneNote", "Excel"]],
    ["Dans un e-mail, que signifie « Cc » ?", ["Copie carbone", "Courrier confidentiel", "Contact client", "Copie certifiée"]],
    ["Dans un e-mail, que signifie « Cci » ?", ["Copie carbone invisible", "Courrier confidentiel interne", "Copie certifiée individuelle", "Contact client important"]],
    ["Que signifie « KPI » ?", ["Indicateur clé de performance", "Objectif individuel annuel", "Prime de performance trimestrielle", "Indice de productivité interne"]],
    ["Qu'appelle-t-on l'« onboarding » ?", ["L'intégration d'un nouveau collaborateur", "La réunion annuelle d'objectifs", "Le départ en retraite", "La mise à jour d'un logiciel"]],
    ["Que signifie « CSE » en entreprise ?", ["Comité social et économique", "Conseil de surveillance de l'entreprise", "Commission de suivi des emplois", "Comité de sécurité et d'éthique"]],
    ["Quel organisme collecte les cotisations sociales des entreprises ?", ["L'Urssaf", "France Travail", "La CAF", "L'Insee"]],
  ]),

  ...theme("Informatique", [
    ["Que signifie « HTML » ?", ["HyperText Markup Language", "High Transfer Machine Language", "Hyperlink Text Management Logic", "Home Tool Markup Language"]],
    ["Qui a fondé Microsoft avec Bill Gates ?", ["Paul Allen", "Steve Jobs", "Steve Wozniak", "Larry Page"]],
    ["Combien de bits contient un octet ?", ["8", "4", "16", "32"]],
    ["Quel langage sert principalement à mettre en forme les pages web ?", ["CSS", "Python", "SQL", "Java"]],
    ["En quelle année le premier iPhone a-t-il été présenté ?", ["2007", "2005", "2009", "2010"]],
    ["Que signifie « RGPD » ?", ["Règlement général sur la protection des données", "Registre général des paiements dématérialisés", "Réseau global de partage de documents", "Règle générale de prévention des défaillances"]],
    ["Que désigne le « CPU » d'un ordinateur ?", ["Le processeur", "La mémoire vive", "La carte graphique", "Le disque dur"]],
    ["Quel langage sert à interroger une base de données relationnelle ?", ["SQL", "HTML", "CSS", "Markdown"]],
    ["Que signifie « URL » ?", ["Uniform Resource Locator", "Universal Remote Link", "User Registration Login", "Unified Routing Layer"]],
    ["Qui a créé le noyau Linux ?", ["Linus Torvalds", "Richard Stallman", "Ken Thompson", "Dennis Ritchie"]],
    ["Quelle entreprise développe le système Android ?", ["Google", "Apple", "Microsoft", "Samsung"]],
    ["Quel système de numération les ordinateurs utilisent-ils en interne ?", ["Le binaire", "Le décimal", "Le romain", "L'octal"]],
    ["Que signifie « IA » ?", ["Intelligence artificielle", "Interface automatique", "Informatique appliquée", "Interconnexion avancée"]],
    ["Quelle entreprise a créé le format PDF ?", ["Adobe", "Microsoft", "Apple", "IBM"]],
    ["Quel raccourci clavier colle le contenu copié ?", ["Ctrl + V", "Ctrl + C", "Ctrl + P", "Ctrl + B"]],
    ["Que désigne un « VPN » ?", ["Un réseau privé virtuel", "Un virus de messagerie", "Un serveur de vidéo", "Un pare-feu matériel"]],
    ["Quel langage de programmation a été créé par Guido van Rossum ?", ["Python", "Ruby", "Java", "Perl"]],
    ["Quel protocole sécurise la navigation web (le cadenas du navigateur) ?", ["HTTPS", "FTP", "SMTP", "HTTP"]],
    ["Qui est considérée comme la première programmeuse de l'histoire ?", ["Ada Lovelace", "Grace Hopper", "Margaret Hamilton", "Hedy Lamarr"]],
    ["Que désigne la « RAM » d'un ordinateur ?", ["La mémoire vive", "La mémoire morte", "Le processeur", "L'alimentation"]],
  ]),

  ...theme("Cuisine", [
    ["De quelle région vient la quiche lorraine ?", ["La Lorraine", "L'Alsace", "La Bourgogne", "La Champagne"]],
    ["Quel fromage met-on traditionnellement dans une tartiflette ?", ["Le reblochon", "Le comté", "Le beaufort", "La raclette"]],
    ["De quel pays viennent les sushis ?", ["Le Japon", "La Chine", "La Corée", "La Thaïlande"]],
    ["Quel est l'ingrédient principal du guacamole ?", ["L'avocat", "La tomate", "Le concombre", "Le poivron"]],
    ["Quel est l'ingrédient principal du houmous ?", ["Le pois chiche", "La lentille", "Le haricot blanc", "La fève"]],
    ["De quel pays vient la paella ?", ["L'Espagne", "Le Portugal", "L'Italie", "Le Mexique"]],
    ["Quel fromage garnit une pizza margherita ?", ["La mozzarella", "Le parmesan", "Le gorgonzola", "La ricotta"]],
    ["Avec quoi cuisine-t-on traditionnellement le bœuf bourguignon ?", ["Du vin rouge", "De la bière", "Du cidre", "Du vin blanc"]],
    ["Quelle est la base d'une mayonnaise ?", ["Du jaune d'œuf et de l'huile", "Du blanc d'œuf et du beurre", "De la crème et de l'huile", "Du lait et de la farine"]],
    ["Comment appelle-t-on un croque-monsieur surmonté d'un œuf ?", ["Un croque-madame", "Un croque-mademoiselle", "Un croque-œuf", "Un croque-baron"]],
    ["Le cassoulet est une spécialité de quelle région ?", ["L'Occitanie", "La Bretagne", "L'Alsace", "La Normandie"]],
    ["Quelle pâtisserie en pâte à choux, longue et glacée, est fourrée de crème ?", ["L'éclair", "Le mille-feuille", "Le paris-brest", "Le baba au rhum"]],
    ["Quelle épice est la plus chère du monde ?", ["Le safran", "La vanille", "La cardamome", "Le poivre"]],
    ["De quelle région vient le kouign-amann ?", ["La Bretagne", "La Normandie", "Le Pays basque", "La Savoie"]],
    ["De quel pays vient le tiramisu ?", ["L'Italie", "L'Espagne", "La Grèce", "L'Autriche"]],
    ["Qu'est-ce que le saint-nectaire ?", ["Un fromage", "Un vin", "Une charcuterie", "Un dessert"]],
    ["Comment se sert traditionnellement le gaspacho ?", ["Froid", "Chaud", "Flambé", "Gratiné"]],
    ["Quelle céréale est à la base des sushis ?", ["Le riz", "Le blé", "L'orge", "Le maïs"]],
    ["De quelle ville la bouillabaisse est-elle la spécialité ?", ["Marseille", "Lyon", "Bordeaux", "Nice"]],
    ["Quel plat est l'emblème de la Belgique ?", ["Les moules-frites", "La fondue", "La choucroute", "Le cassoulet"]],
  ]),
];
